### ISSUE TITLE
Is it posible to use USB port for FPGA programming?

### ISSUE THREAD

**Issue by nhatuan84** [wilhelmzeuschner/spartan-6-xc6slx9-rz-easyfpga-x1#1]
Hi,

I am new to FPGA and have just bought thid board for learning. I would like to ask you:
Is it posible to use USB port for FPGA programming?

Thanks.

**Comment by wilhelmzeuschner** [comment]
That is not possible. The USB port only provides power and a USB to serial interface.
The chip used for that is the CP2102.
To program the FPGA you need a dedicated programmer.
